version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: chatbot-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    build: .
    container_name: chatbot-backend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      context: ../Front_End-ChatBot-Sarcastic    # caminho até a pasta do front-end
      dockerfile: Dockerfile                     # o nome do Dockerfile do front
    container_name: chatbot-frontend
    restart: always
    ports:
      - "5173:80"                                # 80 é o Nginx, 5173 é o acesso local
    depends_on:
      - backend                                  # sobe depois que o backend estiver pronto
    networks:
      - chatbot-network                          # mesma rede para comunicação direta

volumes:
  mysql_data:

networks:
  chatbot-network:
    driver: bridge
